#!/usr/bin/env bash



case $1 in
  "package")
    mvn clean package
    ;;
  "test")
    mvn clean test 
    ;;
  "run")
    mvn clean package
    sudo java -jar target/Kivarino-Web-1.0-SNAPSHOT-shaded.jar 
    ;;
  "compile")
    mvn clean package
    native-image -O3 -jar target/Kivarino-Web-1.0-SNAPSHOT-shaded.jar 
    ;;
  *)
    printf "unsupported command; %s\n" $1
    ;;


  esac
